# Знакомство с PyTorch

Сейчас мы познакомимся с библиотекой *PyTorch*. Он очень похож на *NumPy*, и сейчас вы в этом убедитесь!

А почему именно *PyTorch*? Почитать можно [здесь](https://habr.com/ru/post/334380/).

## Вспоминаем *NumPy* и сравниваем операции в *PyTorch*

Мы можем создавать матрицы, перемножать их, складывать, транспонировать и в целом совершать любые матричные операции

In [1]:
import numpy as np 

import torch
import torchvision

import torch.nn as nn
import torch.nn.functional as F

import matplotlib.pyplot as plt

In [2]:
np.random.seed(42)

a = np.random.rand(5, 3) # создали случайную матрицу 
a

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [3]:
print("Проверили размеры : %s\n" % (a.shape,))

Проверили размеры : (5, 3)



In [4]:
print("Добавили 5 :\n%s\n" % (a + 5))

Добавили 5 :
[[5.37454012 5.95071431 5.73199394]
 [5.59865848 5.15601864 5.15599452]
 [5.05808361 5.86617615 5.60111501]
 [5.70807258 5.02058449 5.96990985]
 [5.83244264 5.21233911 5.18182497]]



## Задание

Умножьте матрицу `а` на транспонированную матрицу `а`.  

Чему равен самый первый элемент результата?  
Ответ округлите до сотых.

In [5]:
a @ a.T

array([[1.57995312, 0.48673782, 1.28525324, 0.9947397 , 0.64675177],
       [0.48673782, 0.40706809, 0.26368252, 0.57840584, 0.55984141],
       [1.28525324, 0.26368252, 1.11497408, 0.64198458, 0.34157207],
       [0.9947397 , 0.57840584, 0.64198458, 1.44251562, 0.77015453],
       [0.64675177, 0.55984141, 0.34157207, 0.77015453, 0.77110897]])

In [6]:
print("Среднее по колонкам :\n%s\n" % (a.mean(axis=-1)))

Среднее по колонкам :
[0.68574946 0.30355721 0.50845826 0.56618897 0.40886891]



In [7]:
print("Изменили размеры :\n%s\n" % (a.reshape(3, 5).shape,))

Изменили размеры :
(3, 5)



## Задание

При помощи *NumPy* посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [12]:
(np.arange(1, 10001, 1)**2).sum()

333383335000

Аналогичные операции в *PyTorch* выглядят следующим образом, синтаксис отличается, но совсем немного:

In [13]:
x = torch.rand(5, 3)
x

tensor([[0.9179, 0.5030, 0.6434],
        [0.4667, 0.6165, 0.0383],
        [0.2693, 0.3927, 0.3582],
        [0.8210, 0.0365, 0.3163],
        [0.5787, 0.0729, 0.3927]])

In [14]:
print("Проверили размеры : %s\n" % (x.shape,))

Проверили размеры : torch.Size([5, 3])



In [15]:
print("Добавили 5 :\n%s\n" % (x + 5))

Добавили 5 :
tensor([[5.9179, 5.5030, 5.6434],
        [5.4667, 5.6165, 5.0383],
        [5.2693, 5.3927, 5.3582],
        [5.8210, 5.0365, 5.3163],
        [5.5787, 5.0729, 5.3927]])



In [16]:
print("X*X^T  (1):\n%s\n" % (torch.matmul(x, x.transpose(1, 0))))
print("X*X^T  (2):\n%s\n" % (x.mm(x.t())))

X*X^T  (1):
tensor([[1.5096, 0.7631, 0.6752, 0.9755, 0.8205],
        [0.7631, 0.5994, 0.3816, 0.4178, 0.3300],
        [0.6752, 0.3816, 0.3551, 0.3488, 0.3251],
        [0.9755, 0.4178, 0.3488, 0.7755, 0.6020],
        [0.8205, 0.3300, 0.3251, 0.6020, 0.4944]])

X*X^T  (2):
tensor([[1.5096, 0.7631, 0.6752, 0.9755, 0.8205],
        [0.7631, 0.5994, 0.3816, 0.4178, 0.3300],
        [0.6752, 0.3816, 0.3551, 0.3488, 0.3251],
        [0.9755, 0.4178, 0.3488, 0.7755, 0.6020],
        [0.8205, 0.3300, 0.3251, 0.6020, 0.4944]])



In [17]:
print("Среднее по колонкам :\n%s\n" % (x.mean(dim=-1)))

Среднее по колонкам :
tensor([0.6881, 0.3738, 0.3401, 0.3913, 0.3481])



In [18]:
print("Изменили размеры :\n%s\n" % (x.view([3, 5]).shape,))
print("Изменили размеры :\n%s\n" % (x.view_as(x.t()).shape,))

Изменили размеры :
torch.Size([3, 5])

Изменили размеры :
torch.Size([3, 5])



Небольшой пример того, как меняются операции:

* `x.reshape([1,2,8]) -> x.view(1,2,8)`

* `x.sum(axis=-1) -> x.sum(dim=-1)`

* `x.astype('int64') -> x.type(torch.LongTensor)`

Для помощи вам есть [таблица](https://github.com/torch/torch7/wiki/Torch-for-Numpy-users), которая поможет вам найти аналог операции в *NumPy*.


При помощи *PyTorch* посчитаем сумму квадратов натуральных чисел от 1 до 10000.

In [19]:
torch.sum(torch.range(1, 10000) ** 2)

<ipython-input-19-b9d129fd8adb>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.sum(torch.range(1, 10000) ** 2)


tensor(3.3338e+11)

Создаем тензоры в *PyTorch* и снова изучаем базовые операции

In [20]:
x = torch.empty(5, 3) # пустой тензор
print(x)

tensor([[ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  1.5588e-34,  0.0000e+00],
        [ 3.1706e-35,  0.0000e+00, -2.5784e-36],
        [ 4.5834e-41,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])


In [21]:
x = torch.rand(5, 3) # тензор со случайными числами
print(x)

tensor([[0.9796, 0.7963, 0.1787],
        [0.2086, 0.6573, 0.1459],
        [0.2888, 0.6491, 0.0057],
        [0.1564, 0.1272, 0.4018],
        [0.8209, 0.2454, 0.8148]])


In [22]:
x = torch.zeros(5, 3, dtype=torch.long) # тензор с нулями и указанием типов чисел
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [23]:
x = torch.tensor([5.5, 3]) # конструируем тензор из питоновского листа
print(x)

tensor([5.5000, 3.0000])


In [24]:
x = x.new_ones(5, 3, dtype=torch.double) # используем уже созданный тензор для создания тензора из единичек
print(x, x.size()) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) torch.Size([5, 3])


In [25]:
x = torch.randn_like(x, dtype=torch.float) # создаем матрицу с размерами как у x
print(x, x.size())

tensor([[-1.8440, -0.6339, -0.6537],
        [-2.7656, -1.6009, -0.5328],
        [ 0.1742,  0.4293,  2.8787],
        [ 0.7435, -0.7573,  1.9120],
        [-0.4583, -0.0034, -0.3040]]) torch.Size([5, 3])


## Задание

Сгенерируйте два тензора: `x` и `y` размера 5 на 3 со случайными числами.
Вычислите сумму тензоров `x` и `y`.

В ответе напишите значение первой координаты в полученной суммы, округленной до сотых.

In [28]:
torch.manual_seed(42)
x = torch.rand(5, 3)
y = torch.rand(5, 3)
x + y
# your code here

tensor([[1.3117, 1.8004, 0.9568],
        [1.2259, 1.0179, 0.8705],
        [0.6979, 1.0906, 1.7725],
        [0.2385, 1.2041, 0.9524],
        [1.0688, 1.1149, 0.7473]])

In [27]:
print(x * y) # поэлементное умножение

tensor([[0.3789, 0.8102, 0.2197],
        [0.2557, 0.2450, 0.1620],
        [0.1132, 0.2356, 0.7824],
        [0.0140, 0.2519, 0.2130],
        [0.1733, 0.3106, 0.0046]])


## Задание

Умножьте матрицу `x` на транспонированную матрицу `y`.

В ответ напишите последний элемент (правый нижний) полученной матрицы.  
Ответ округлите до сотых.

In [29]:
x @ y.T

tensor([[1.4088, 0.9125, 0.9795, 0.4769, 0.6789],
        [1.1025, 0.6627, 1.0391, 0.4219, 0.4086],
        [1.3528, 0.8200, 1.1313, 0.5785, 0.4912],
        [1.2254, 0.7820, 0.8300, 0.4789, 0.5416],
        [1.3013, 0.7878, 1.1686, 0.5105, 0.4885]])

In [ ]:
print(x.unsqueeze(0).shape) # добавили измерение в начало, аналог броадкастинга 

torch.Size([1, 5, 3])


In [ ]:
print(x.unsqueeze(0).squeeze(0).shape) # убрали измерение в начале, аналог броадкастинга 

torch.Size([5, 3])


In [ ]:
a = torch.rand((1,3))
a

tensor([[0.8823, 0.9150, 0.3829]])

In [ ]:
a.squeeze(0)

tensor([0.8823, 0.9150, 0.3829])

Мы также можем делать обычные срезы и переводить матрицы назад в *NumPy*:

In [ ]:
a = np.ones((3, 5))
x = torch.ones((3, 5))
print(np.allclose(x.numpy(), a))
print(np.allclose(x.numpy()[:, 1], a[:, 1]))

True
True


In [ ]:
a = np.array([1,2,3,4])
b = np.array([[5],[6],[7],[8]])

a.shape, b.shape

((4,), (4, 1))

In [ ]:
a @ b

array([70])

In [ ]:
b @ a

ValueError: ignored